version: '3'

services:
  postgres_database:
    container_name: postgres_web
    image: 'postgres:15'
    hostname: postgres_database
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5435:5435
    command: "-p 5435"
  
  training_app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null 
    working_dir: /home/app
    container_name: django_training
    volumes: 
      - .:/home/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_database




